// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by:
//        'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator'
//
//    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

public static class GdkPlatformSettings
{
#if UNITY_GAMECORE_XBOXONE
    public static string gameConfigTitleId = "74F15AAF";
    public static string gameConfigScid = "00000000-0000-0000-0000-000074f15aaf";
    [Obsolete("gameConfigSandbox will be removed in future releases. Please do not use.", false)]
    public static string gameConfigSandbox = "";
#elif UNITY_GAMECORE_XBOXSERIES
    public static string gameConfigTitleId = "625AE781";
    public static string gameConfigScid = "00000000-0000-0000-0000-0000625ae781";
    [Obsolete("gameConfigSandbox will be removed in future releases. Please do not use.", false)]
    public static string gameConfigSandbox = "";
#else
    public static string gameConfigTitleId = "75844E0A";
    public static string gameConfigScid = "00000000-0000-0000-0000-000075844e0a";
    [Obsolete("gameConfigSandbox will be removed in future releases. Please do not use.", false)]
    public static string gameConfigSandbox = "";
#endif
}
