// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by:
//        'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator'
//
//    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

public static class GdkPlatformSettings
{
#if UNITY_GAMECORE_XBOXONE
    public static string gameConfigTitleId = "67607924";
    public static string gameConfigScid = "00000000-0000-0000-0000-000067607924";
    [Obsolete("gameConfigSandbox will be removed in future releases. Please do not use.", false)]
    public static string gameConfigSandbox = "";
#elif UNITY_GAMECORE_XBOXSERIES
    public static string gameConfigTitleId = "7c509066";
    public static string gameConfigScid = "00000000-0000-0000-0000-00007c509066";
    [Obsolete("gameConfigSandbox will be removed in future releases. Please do not use.", false)]
    public static string gameConfigSandbox = "";
#else
    public static string gameConfigTitleId = "79962B79";
    public static string gameConfigScid = "00000000-0000-0000-0000-000079962b79";
    [Obsolete("gameConfigSandbox will be removed in future releases. Please do not use.", false)]
    public static string gameConfigSandbox = "";
#endif
}
